### ISSUE TITLE
Implement generic plotting tool for sentiment metrics

### ISSUE THREAD

**Issue by wengandrew** [wengandrew/battery-talent-census#10]
Some survey questions ask for respondents to provide a sentiment rating between 1-5. These responses are processed in a specific way by `Analyst`. For these data types, develop a generic plotter to quickly visualize the data. Implement this method in `Plotter`.

**Comment by dzh-ad** [comment]
Could maybe make this a generic histogram plotter, so we can use it for salary (and any other number-based responses) as well?
