### ISSUE TITLE
Remove 'mean' and 'stdev' from sentiment aggregator methods

### ISSUE THREAD

**Issue by wengandrew** [wengandrew/battery-talent-census#19]
Get rid of these statistics since they'll most likely have to be recalculated again once the user applies their own filters (e.g., outlier exclusion rules).

This applies to statistics that aren't for the "sentiment" metrics which already have a finite range (1-5)

**Comment by dzh-ad** [comment]
Do you mean remove 'mean' and 'stdev' from aggregator methods that are not on sentiment?
