### ISSUE TITLE
Suggestion: Update plot font to "Inter"

### ISSUE THREAD

**Issue by dzh-ad** [wengandrew/battery-talent-census#2]
Update font to "Inter" to:

1. to match with 2024 Battery Report format
2. allow both Mac and non-Mac contributors to create plot without the error "missing Helvetica"

It's a nice open source Google font available for download [here](https://fonts.google.com/specimen/Inter)

**Comment by dzh-ad** [comment]
If yes:
1. update README to ask contributors to download Inter
2. update `set_aesthetics` in `plotter`

**Comment by wengandrew** [comment]
Good suggestion. Go ahead and make a PR with the proposed changes.

**Comment by wengandrew** [comment]
We could also define a standard colormap to match VF branding. IT could be kept inside `Plotter` as constants, e.g., `BLUE = '...'`, `BLUE2 = '...'`.
